### ISSUE TITLE
Get rid of arbitrary strings in file types

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#141]
Right now datamodel allows arbitrary strings in filenode's type field.

We should restrict that, via a enum in the protobuf description, to source, intermediate and target.

**Comment by GiasemiSh** [comment]
File types can not be an enum type. We use the file types in the dgraph schema which supports only scalar types and the UID type.

**Comment by GiasemiSh** [comment]
Use protobuf oneof
