### ISSUE TITLE
let scan code analyzer scan uploaded files

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#143]
Since code that was passed via stdin gets uploaded to QMSTR_pushFiles, to not mess with the actual sources, it will not be scanned by scan code.

Either use source sets as mentioned in  #142 or adapt scancode analyzer to scan several directories. 
Anyway it needs to handle a scancode results per source directory.

**Comment by GiasemiSh** [comment]
Scan code runs on the buildroot and as a consequence it scans also the uploaded files.
