### ISSUE TITLE
Extend qmstrctl to be able to add custom nodes to the graph

### ISSUE THREAD

**Issue by thegrumpylion** [QMSTR/qmstr-all#161]

**Comment by thegrumpylion** [comment]
@mirkoboehm Please explain a bit what you would like to see in this functionality

**Comment by hemarkus** [comment]
What is the purpose for this? BTW we already have the missing pieces analyzer that can add and change all kinds of nodes in the graph.

**Comment by thegrumpylion** [comment]
Superseded by #189 - #192
