### ISSUE TITLE
Commit generated *.pb.go files to the repository

### ISSUE THREAD

**Issue by thegrumpylion** [QMSTR/qmstr-all#164]
Files generated by the means of "protoc ..." should be commited in the repository for proper versioning and also get rid of build time and dev dependencies like the proto compiler, protoc-gen-go, libraries, etc.

**Comment by hemarkus** [comment]
I don't think generated files should ever be commited into a repository. Sooner or later someone will edit generated files and everything breaks when new stuff is added to the proto files. I have seen this way too often.

Also I don't see what kind of problem this issue addresses.

**Comment by hemarkus** [comment]
Superseded by #174
