### ISSUE TITLE
Fix dependency management in the project

### ISSUE THREAD

**Issue by thegrumpylion** [QMSTR/qmstr-all#165]
Currently QMSTR uses dep for dependency management. We should either:

* Use dep properly by commiting Gopkg.lock to the repo.
* Migrate to go mod

**Comment by thegrumpylion** [comment]
After some back and forth with Markus, the choice is obvious. Go mod is the way to go (no pun intended) since is build into the whole go tooling, and many more.

**Comment by thegrumpylion** [comment]
The steps for this should be simple

`go mod init`
`go mod tidy`

But this fails with

`...`
`go: github.com/Sirupsen/logrus@v1.3.0: parsing go.mod: unexpected module path "github.com/sirupsen/logrus"`
`go: error loading module requirements`

The reason is that it pulls an old version of docker that depends on a a path with upercase letter. After digging around it seems this will not be an issue with go 1.12

Even if you try manually pulling docker by the means of

`go mod init`
`go get github.com/docker/docker@v17.05.0-ce`
`go mod tidy`

it still fails with the same issue. The reason being that v17.05.0-ce (which is the latest?) is relatively old (2017-05-04)

A solution to this is pulling a version i found in this https://github.com/golang/go/issues/26208 which is from 2018-04-22

`go mod init`
`go get github.com/docker/docker@v0.0.0-20180422163414-57142e89befe`
`go mod tidy`

So this got me thinking that versions from that date an on should also work. So i tried with pulling docker master and it worked as expected.

`go mod init`
`go get github.com/docker/docker@master`
`go mod tidy`

So the question becomes on which commit of the docker repository do we want to depend on? We can try building with current master and if everything works we can stick with that until we find a better version to update to.

@hemarkus any input?

**Comment by thegrumpylion** [comment]
Let's wait for golang 1.12 to be out and look into this again

**Comment by hemarkus** [comment]
Find task for migration here https://github.com/QMSTR/qmstr/issues/262
