### ISSUE TITLE
Add  "describe <node>" command to the cli

### ISSUE THREAD

**Issue by thegrumpylion** [QMSTR/qmstr-all#166]
qmstrctl node dump ... should be added to have the ability to inspect individual nodes.

TODO:

* pkg/analyze/GetFileNode should become more generic in order to support other queries like for example path, name, etc. not just type

Note: Review with Markus

**Comment by GiasemiSh** [comment]
For the above TODO, there is a pull Request: https://github.com/QMSTR/qmstr/pull/201

**Comment by hemarkus** [comment]
@GiasemiSh can we close this issue?

**Comment by GiasemiSh** [comment]
@hemarkus Yes
