### ISSUE TITLE
Create CI pielines for new repos

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#183]
After splitting up the mono QMSTR/qmstr repo we need CI for those new repositories.

**Comment by mirkoboehm** [comment]
@hemarkus This potentially conflicts with the upcoming next reorganisation of the main repo?

**Comment by hemarkus** [comment]
> @hemarkus This potentially conflicts with the upcoming next reorganisation of the main repo?
Indeed
