### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#23]
We need CI to monitor the build quality. Let's:
* set up a job for the Go build of the qmstr repo
* set up a job for the build of the QMSTR master container image
Auto-testing the demo cases will be the next step after this.

**Comment by danielriesner** [comment]
I created the [first one](https://ci.endocode.com/job/QMSTR/job/qmstr_compile_test/configure) of the two requested jenkins jobs.

The job is supposed to be triggered by pull requests ("GitHub Pull Request Builder") in the qmstr github repo and starts automatically if the pull request was done by someone inside Endocode github organisation. For compiling qmstr I reused parts of [Markus Dockerfile](https://github.com/QMSTR/qmstr-container) for running qmstr in a docker container: Setting up go env, installing go and running the install.sh script. Not so nice probably is the way the Dockerfile is placed into the workspace. I use a heredoc to create the file.

Please check if you think it fits the demands. Thanks!

**Comment by danielriesner** [comment]
There is now a public, unlisted [jenkins job](https://ci.endocode.com/view/QMSTR/job/QMSTR/job/build_and_unit_test/) for building qmstr and running its unit tests for pull requests (--target builder). Right now it is only triggered by pull requests made by github users of endocode organisation. But if I got it right Mirko you said to change it so the job runs for every pull request?

Also there is a [jenkins job](https://ci.endocode.com/view/QMSTR/job/QMSTR/job/create_master_docker_image/) for building the complete master image. At the moment it is deactivated.
