### ISSUE TITLE
Create sample skeleton analyzers and reporters

### ISSUE THREAD

**Issue by GiasemiSh** [QMSTR/qmstr-all#29]
Sample skeletons of analysis tools and reporters to show supporting of external user tools.

**Comment by mirkoboehm** [comment]
Based on today's discussion in the daily:

- Implement an analyser that compares the author (not copyright holder) that ScanCode identified with the (one, two, three) top authors as identified by `git blame`. Matches are "good", Mismatches are "warnings, missing authors are "errors".
- Implement a reporter that lists the warnings.

**Comment by hemarkus** [comment]
Depends on #36

**Comment by mirkoboehm** [comment]
Re-visit after 0.1.
