### ISSUE TITLE
Implement package manager on wrapper  [not introducing qmstr-proxy]

### ISSUE THREAD

**Issue by GiasemiSh** [QMSTR/qmstr-all#4]
qmstr-proxy idea: Since master is running in a container it can not access host file system. 
We need a tool on host which will use the package manager for analysis and look up system libraries.
Another upside is that we can offload the wrapper and keep it lean (e.g. hashing).

**Comment by hemarkus** [comment]
depends on #8

**Comment by GiasemiSh** [comment]
In the end introducing a qmstpr-proxy won't help us. In the wrapper during the linking step we have all the information we need. We can identify the libs and run package manager. No need to implement an extra binary and pass all the information we already have to it.

**Comment by hemarkus** [comment]
This was not supposed to be in this sprint.
