### ISSUE TITLE
Pin all dependencies to known-good versions

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#41]
Stuff keeps breaking because our dependencies change. All dependency programs should be installed in fixed known-good versions for the release. 

For subsequent releases, dependencies will be updated in a separate PR. This means CI should catch if, e.g., the command line interface of ScanCode or the ports in DGraph change.

**Comment by hemarkus** [comment]
Scancode is pinned already

**Comment by hemarkus** [comment]
dgraph should be pinned to 1.0.4
