### ISSUE TITLE
SPDX package metadata analyzer module

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#49]
To import the package metadata, we need to be able to read SPDX files during analysis. It contains information as:

- Package Name
- Package SPDX Identifier
- Package Version
- Package Supplier

...and so on. We need to be able to read both tag-value and XML/RDF formats. We do not necessarily need our own parser, if existing tools support what we need.

**Comment by hemarkus** [comment]
Looks like we should use this one https://github.com/spdx/tools-python
