### ISSUE TITLE
qmstrctl should give more feedback

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#51]
The qmstr-cli should print more feeback about what the master does. This should be printed if a verbose flag is enabled.

**Comment by hemarkus** [comment]
Also the annoying "connecting to address ..." message should only be printed in verbose mode.

**Comment by hemarkus** [comment]
Maybe use the control service to stream event messages to the client.

**Comment by mirkoboehm** [comment]
Markus and I just discussed this:

- The master container should not exit on an error. It should switch to a failure state (next to construct/analyze/report).
- The control service should always run.
- The control service should always be able to report the master status (in text), or an error message like "Cannot start QMSTR Server: open /buildroot/qmstr.yaml: no such file or directory".
- `qmstrctl wait` should exit if the master is in failure state and print a reasonable error message.
