### ISSUE TITLE
Every module should have a module and an instance name

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#57]
Since more than one instance of a module can be executed in a single QMSTR run, modules need an instance name. The instance name should be used to point to the cache and output directories. Both names should have a standard "human readable" version that may include spaces et cetera, and a "slugified" version that can be used on the filesystem (no spaces, et cetera).

**Comment by hemarkus** [comment]
Both names?

**Comment by hemarkus** [comment]
https://github.com/QMSTR/qmstr/pull/72
