### ISSUE TITLE
Next to package and revision, we need a configuration

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#67]
A configuration refers to a specific build of the package. There can be multiple sets of reports per revision with different configurations.

**Comment by hemarkus** [comment]
This is totally unclear to me. Please clarify.

**Comment by mirkoboehm** [comment]
The structure of the generated web site documents needs one more layer, because site/package/revision refers to source code, whereas site/package/revision/configuration refers to a build. Example:

Endocode/Linux/ABCDEFG1/amd_64_nexus5x
Endocode/Linux/ABCDEFG1/intel_386_runningshoe

The configuration is an arbitrary name given by the vendor.

**Comment by mirkoboehm** [comment]
More details:

* If no configuration name is specified, it defaults to "default".
* If the configuration name is specified by the user, it cannot be empty.
* The configuration name can be specified in the top level section of the YAML file.
* The configuration name can also be specified on `qmstrctl start --configuration amd_64_nexus5x`. This trumps the YAML file setting.

**Comment by mirkoboehm** [comment]
If I would this "Product" instead of "Configuration", maybe people understand what I mean :-)
