### ISSUE TITLE
Module output directory defaults

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#77]
There should be a sensible default for handling the output directory:
- [ ] If nothing is configured, the output directory is provided by the master. `qmstrctl report` copies the results into the build directory (./qmstr/<modulename>/).
- [ ] If the output directory is specified as a volume, it is used and the results are *not* copied by `qmstrctl report`.
- [ ] `qmstrctl report` needs a switch to disable auto-copying of the results.
(sensible default: it works well if the user configures nothing)

**Comment by hemarkus** [comment]
done but via quit command
