### ISSUE TITLE
Load/save intermediate states to a cache

### ISSUE THREAD

**Issue by mirkoboehm** [QMSTR/qmstr-all#78]
QMSTR needs to be able to make intermediate results available to a later run. The reason is that the assumption that the life cycle of the master always matches that of the build does not always hold. The structure of builds in CI follows different logic. For example, a build may be broken up into basic elements and multiple steps that depend on it for performance reasons. This happens for example during the build of Qt between the QtCore library and the applications that depend on it.

A preliminary requirements discussion resulted in this approach:
- The intermediate results will only be available within a QMSTR installation and depend on the specific QMSTR version they are created with. The data format will not be specified.
- The data will be saved in the master section of the cached data directory.
- Every "snapshot" will essentially be a directory, and will be referred to by name.
- There is a "save" and a "load" function in `qmstrctl`.

**Comment by hemarkus** [comment]
refs #93
