### ISSUE TITLE
Global configuration, local configuration

### ISSUE THREAD

**Issue by hemarkus** [QMSTR/qmstr-all#98]
-   The cache directory should be configured at the machine level.
    -   /etc/qmstr/qmstr.yaml
        -   cachedir: "/var/cache/qmstr"
-   The config file should be "moveable" so that the repository under
    analysis contains no changes compared to upstream.
    -   qmstrctl start –config ../qmstr.yaml

**Comment by mirkoboehm** [comment]
I think these should be two tickets. Priority for the moment is the secind part (the config file should be "moveable" so that the repository under analysis contains no changes compared to upstream).
